In [1]:
import numpy as np
a = np.arange(12).reshape(3,4)

In [4]:
a[:,:1]

array([[0],
       [4],
       [8]])

In [6]:
a[:,1:2*1]

array([[1],
       [5],
       [9]])

In [8]:
a[:,:4]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
a[:,4:2*4]

array([], shape=(3, 0), dtype=int32)